-- Update panduan Upload Lampiran SPM (Bendahara OPD)
UPDATE panduan_manual 
SET konten = '<h3>Lampiran yang Diperlukan</h3><p>SPM dikelompokkan dalam 4 kategori lampiran:</p><ul><li><strong>Dokumen SPM</strong>: SPP, SPM, Ringkasan SPP, Rincian SPP, RAB, dan dokumen pendukung utama</li><li><strong>TBK/Kuitansi</strong>: Invoice, kuitansi, bukti pembayaran, dan dokumen penagihan</li><li><strong>SPJ</strong>: Surat Pertanggungjawaban dan dokumen terkait pertanggungjawaban</li><li><strong>Lainnya</strong>: Dokumen pendukung tambahan seperti rekening koran, surat pernyataan, dll</li></ul><p><strong>Khusus untuk SPM LS Barang/Jasa dan Belanja Modal:</strong></p><ul><li>Kontrak/SPK wajib diupload</li><li>Berita Acara Serah Terima (BAST) wajib diupload</li><li>Foto barang (jika diperlukan)</li></ul><p>Format file yang diterima: PDF, JPG, PNG. Ukuran maksimal per file sesuai konfigurasi sistem (default 5MB)</p>', 
    updated_at = now() 
WHERE id = '88f3aa90-df7a-4dd1-9f9c-e522f28a5f1b';

-- Update panduan Tracking Status SPM (Bendahara OPD)
UPDATE panduan_manual 
SET konten = '<h3>Cara Cek Status Verifikasi</h3><p>Anda dapat memantau progress SPM melalui:</p><ol><li>Masuk ke <strong>Input SPM</strong></li><li>Klik salah satu SPM untuk melihat detail</li><li>Timeline verifikasi akan menampilkan:<ul><li>✅ <strong>Resepsionis</strong> - Pemberian nomor antrian & berkas</li><li>✅ <strong>PBMD</strong> - Verifikasi kelengkapan aset (khusus SPM dengan centang "Is Aset")</li><li>✅ <strong>Akuntansi</strong> - Validasi jurnal & kode rekening</li><li>✅ <strong>Perbendaharaan</strong> - Verifikasi ketersediaan anggaran</li><li>✅ <strong>Kepala BKAD</strong> - Approval akhir (memerlukan PIN)</li></ul></li></ol><p><strong>Catatan:</strong> Tidak semua SPM melewati PBMD. Hanya SPM yang ditandai sebagai "Is Aset" yang akan melewati tahap verifikasi PBMD.</p><p>Jika ada revisi di tahap mana pun, status akan berubah menjadi "Perlu Revisi" dan Anda akan menerima notifikasi beserta catatan perbaikan.</p>', 
    updated_at = now() 
WHERE id = '62dd2e55-4950-4135-bca2-1e05cc7d616a';

-- Update panduan Tugas PBMD
UPDATE panduan_manual 
SET konten = '<h2>Panduan Verifikasi PBMD</h2><p>Petugas Pengelola Barang Milik Daerah (PBMD) bertanggung jawab atas:</p><ul><li>Verifikasi kelengkapan dokumen pengadaan barang/jasa</li><li>Pengecekan kontrak/SPK dan BAST</li><li>Memastikan sesuai dengan inventaris dan aset daerah</li></ul><p><strong>PENTING:</strong> Verifikasi PBMD <strong>HANYA</strong> berlaku untuk SPM yang ditandai sebagai <strong>"Is Aset"</strong>. SPM non-aset akan langsung ke tahap Akuntansi setelah Resepsionis.</p><p>Alur verifikasi:</p><ul><li>SPM <strong>dengan centang Is Aset</strong>: Resepsionis → <strong>PBMD</strong> → Akuntansi → Perbendaharaan → Kepala BKAD</li><li>SPM <strong>tanpa centang Is Aset</strong>: Resepsionis → Akuntansi → Perbendaharaan → Kepala BKAD</li></ul>', 
    updated_at = now() 
WHERE id = '6c92e0a8-a4c4-4d17-a82d-b6faebf5e634';

-- Update panduan Checklist Verifikasi PBMD
UPDATE panduan_manual 
SET konten = '<h3>Dokumen yang Harus Diperiksa</h3><p><strong>Untuk SPM yang masuk ke PBMD (ditandai "Is Aset"):</strong></p><ul><li><strong>Kontrak/SPK</strong>: Apakah sudah ditandatangani lengkap oleh kedua belah pihak?</li><li><strong>BAST (Berita Acara Serah Terima)</strong>: Sudah ada tandatangan pihak terkait dan sesuai dengan kontrak?</li><li><strong>Invoice/Kuitansi</strong>: Nilai sesuai dengan kontrak dan termin yang disetujui?</li><li><strong>Spesifikasi Barang/Jasa</strong>: Sesuai dengan yang tercantum dalam kontrak dan dokumen pengadaan?</li><li><strong>Foto Barang</strong>: Jika diperlukan, dokumentasi fisik barang yang diserahkan</li><li><strong>Surat Jalan/Delivery Order</strong>: Bukti pengiriman barang (jika ada)</li></ul><p><strong>Kategori Lampiran di Sistem:</strong></p><ul><li>Dokumen SPM</li><li>TBK/Kuitansi</li><li>SPJ</li><li>Lainnya</li></ul><p>Jika semua dokumen sudah sesuai dan lengkap, lakukan <strong>Approve</strong>. Jika ada ketidaksesuaian atau dokumen kurang, berikan <strong>Revisi</strong> dengan catatan yang jelas dan detail agar Bendahara bisa segera melengkapi.</p>', 
    updated_at = now() 
WHERE id = 'b02c3748-039c-40ae-b110-8e00d6c0e623';

-- Update panduan Cara Approval Kepala BKAD
UPDATE panduan_manual 
SET konten = '<h3>Langkah Approval</h3><ol><li>Buka menu <strong>Approval Kepala BKAD</strong></li><li>Pilih SPM yang akan di-review</li><li>Review seluruh tahap verifikasi yang sudah dilalui:<ul><li>✅ Resepsionis - Kelengkapan dokumen awal</li><li>✅ PBMD - Verifikasi aset (jika SPM ditandai "Is Aset")</li><li>✅ Akuntansi - Validasi kode rekening dan jurnal</li><li>✅ Perbendaharaan - Ketersediaan anggaran</li></ul></li><li>Baca catatan dari setiap tahap verifikasi jika ada</li><li>Pastikan tidak ada catatan revisi yang masih outstanding</li><li>Periksa kembali nilai SPM dan kesesuaiannya dengan dokumen</li><li>Masukkan <strong>PIN</strong> untuk keamanan approval (kecuali dalam Emergency Mode)</li><li>Klik <strong>Approve</strong> jika semua sudah sesuai, atau <strong>Revisi</strong> jika ada yang perlu diperbaiki</li><li>SPM yang disetujui akan berstatus "Disetujui" dan siap untuk proses penerbitan SP2D oleh Kuasa BUD</li></ol><p><strong>PIN Approval:</strong> PIN akan dikirim via WhatsApp/Email setiap kali Anda akan melakukan approval. PIN berlaku untuk waktu terbatas (biasanya 5-10 menit).</p>', 
    updated_at = now() 
WHERE id = '88cc934b-f3e8-4b05-8d2f-234ab73c4840';

-- Update panduan Cara Input SP2D
UPDATE panduan_manual 
SET konten = '<h3>Langkah Input SP2D</h3><ol><li>Buka menu <strong>SP2D</strong></li><li>Klik <strong>Buat SP2D</strong></li><li>Pilih SPM yang sudah disetujui Kepala BKAD (status "Disetujui")</li><li>Sistem akan otomatis:<ul><li>Generate nomor SP2D sesuai format yang dikonfigurasi</li><li>Mengisi nilai SP2D dari SPM</li><li>Menghitung potongan pajak jika ada</li><li>Menghitung nilai yang diterima (nilai SP2D - potongan)</li></ul></li><li>Isi/Verifikasi data rekening tujuan pencairan:<ul><li><strong>Nama Bank</strong>: Sesuai rekening penerima</li><li><strong>Nomor Rekening</strong>: Nomor rekening yang valid</li><li><strong>Nama Penerima</strong>: Sesuai dengan pemilik rekening</li></ul></li><li><strong>Upload Dokumen SP2D</strong> (wajib): File PDF dokumen SP2D yang sudah ditandatangani</li><li>Sistem akan mengirim <strong>OTP</strong> via WhatsApp/Email untuk verifikasi</li><li>Masukkan kode OTP yang diterima</li><li>Klik <strong>Terbitkan SP2D</strong></li><li>SP2D berhasil diterbitkan dan dapat:<ul><li>Dicetak untuk arsip</li><li>Dikirim ke Bank untuk proses pencairan dana</li><li>Dipantau statusnya: Dikirim ke Bank → Diuji Bank → Dicairkan</li></ul></li></ol><p><strong>Tracking SP2D:</strong></p><ul><li><strong>Diterbitkan</strong>: SP2D baru dibuat</li><li><strong>Dikirim ke Bank</strong>: SP2D sudah dikirim ke bank</li><li><strong>Diuji Bank</strong>: Bank sedang memproses</li><li><strong>Dicairkan</strong>: Dana sudah ditransfer ke rekening penerima</li></ul>', 
    updated_at = now() 
WHERE id = 'ae03b3de-8c35-40f2-8262-220eaa8ddba4';